[package]
name = "rusty_flexi"
version = "0.1.0"
authors = ["Geobert Quach <geobert@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
pdcurses-sys = "0.4"
pancurses = "0.9"