[package]
name = "rusty_flexi"
version = "0.1.0"
authors = ["Geobert Quach <geobert@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
gtk = { version = "0.1", features = ["v3_16"] }
pango = "0.1"
futures = "^0.1.14"
#relm = "0.9"
#relm-attributes = "0.9"
#relm-derive = "0.9"
[dependencies.futures-glib]
git = "https://github.com/antoyo/futures-glib-rs"

[dependencies.relm]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-attributes]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-derive]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"
